obj-$(CONFIG_XM_POWER_SUPPLY)	+= fuelgauge_ic/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= charge_pump_ic/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= load_switch_ic/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= boost_ic/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= wireless_ic/

# redriver, subpmic
