obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_platform_buckchg_class.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_platform_fg_ic_ops.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_platform_cp_class.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_platform_wireless_class.o

#   mca_platform_base.o
#   mca_platform_bc12_class.o
#   mca_platform_subpmic_cid_class.o
#   mca_platform_loadsw_class.o
