obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_business_charger_comp.o
mca_business_charger_comp-objs := mca_business_charger.o mca_charger_usb_psy.o mca_charger_wireless_psy.o

CFLAGS_mca_business_charger.o += -Wno-error=incompatible-pointer-types
CFLAGS_mca_charger_usb_psy.o  += -Wno-error=incompatible-pointer-types
