#ifndef _MCA_COMMON_MCA_EVENT_H_
#define _MCA_COMMON_MCA_EVENT_H_

#include <linux/notifier.h>

#define MCA_EVENT_NOTIFY_SIZE 128
#define MCA_EVENT_WR_BUF_SIZE 128

enum mca_event_type {
	MCA_EVENT_TYPE_BEGIN = 0,
	MCA_EVENT_TYPE_CHARGER_CONNECT = MCA_EVENT_TYPE_BEGIN,
	MCA_EVENT_TYPE_CHARGE_TYPE,
	MCA_EVENT_TYPE_BATTERY_INFO,
	MCA_EVENT_TYPE_CP_INFO,
	MCA_EVENT_TYPE_HW_INFO,
	MCA_EVENT_CHARGE_STATUS,
	MCA_EVENT_TYPE_THERMAL_TEMP,
	MCA_EVENT_TYPE_PANEL,
	MCA_EVENT_TYPE_TYPEC_PORT_STATUS,
	MCA_EVENT_TYPE_SUBPMIC_INFO,
	MCA_EVENT_TYPE_END,
};

enum mca_event_code {
	MCA_EVENT_USB_CONNECT = 0x00,
	MCA_EVENT_USB_DISCONNECT = 0x01,
	MCA_EVENT_WIRELESS_CONNECT = 0x02,
	MCA_EVENT_WIRELESS_DISCONNECT = 0x03,
	MCA_EVENT_WIRELESS_REVCHG = 0x04,
	MCA_EVENT_CHARGE_TYPE_CHANGE = 0x05,
	MCA_EVENT_CHARGE_CAP_CHANGE = 0x06,
	MCA_EVENT_CHARGE_VERIFY_PROCESS_END = 0x07,
	MCA_EVENT_BATTERY_STS_CHANGE = 0x11,
	MCA_EVENT_BATTERY_FAKE_POWER = 0x12,
	MCA_EVENT_CP_VUSB_OVP = 0x16,
	MCA_EVENT_CP_VBAT_OVP = 0x17,
	MCA_EVENT_CP_VBUS_OVP = 0x18,
	MCA_EVENT_CP_IBAT_OCP = 0x1c,
	MCA_EVENT_CP_IBUS_OCP = 0x1d,
	MCA_EVENT_CP_CBOOT_FAIL = 0x1f,
	MCA_EVENT_CP_TSHUT_FLAG = 0x22,
	MCA_EVENT_CP_IIC_ERROR = 0x23,
	MCA_EVENT_CONN_ANTIBURN_CHANGE = 0x24,
	MCA_EVENT_BATT_BTB_CHANGE = 0x25,
	MCA_EVENT_BATT_AUTH_PASS = 0x26,
	MCA_EVENT_LPD_STATUS_CHANGE = 0x27,
	MCA_EVENT_PMIC_INIT_DONE = 0x28,
	MCA_EVENT_CC_SHORT_VBUS = 0x29,
	MCA_EVENT_VBAT_OVP_CHANGE = 0x2a,
	MCA_EVENT_IBAT_OCP_CHANGE = 0x2b,
	MCA_EVENT_CP_REVERT_CHANGE = 0x2c,
	MCA_EVENT_USB_STS_CHANGE = 0x2d,
	MCA_EVENT_CP_VUSB_INSERT = 0x2e,
	MCA_EVENT_CP_VUSB_OUT = 0x2f,
	MCA_EVENT_SOC_LIMIT = 0x30,
	MCA_EVENT_BATTERY_DTPT = 0x31,
	MCA_EVENT_CSD_SEND_PULSE = 0x32,
	MCA_EVENT_PANEL_SCREEN_STATE_CHANGE = 0x3c,
	MCA_EVENT_CC_TOGGLE_CHANGE = 0x3d,
	MCA_EVENT_SINK_PWR_SUSPEND_CHANGE = 0x40,
	MCA_EVENT_USB_SUSPEND = 0x41,
	MCA_EVENT_BATTERY_HEALTH_CHANGE = 0x43,
	/*
	 * ------------------------------------------
	 */
	MCA_EVENT_OTG_CONNECT = 0x48,
	MCA_EVENT_OTG_DISCONNECT,
	MCA_EVENT_THERMAL_BOARD_TEMP_CHANGE,
	MCA_EVENT_CID_DISCONNECT,
	MCA_EVENT_CHARGE_ABNORMAL,
	MCA_EVENT_CHARGE_ACTION,
	MCA_EVENT_CHARGE_CANCEL_MONITOR_WORK,
	MCA_EVENT_CHARGE_RESTORE,
	MCA_EVENT_CP_MODE_DEFAULT,
	MCA_EVENT_CP_MODE_FORWARD_1,
	MCA_EVENT_CP_MODE_FORWARD_2,
	MCA_EVENT_CP_MODE_FORWARD_4,
	MCA_EVENT_CP_MODE_CHANGE,
	MCA_EVENT_CP_IBUS_UCP,
	MCA_EVENT_CP_VWPC_OVP,
	MCA_EVENT_CP_VOUT_UVLO,
	MCA_EVENT_CP_PMID2OUT_OVP,
	MCA_EVENT_CP_PMID2OUT_UVP,
	MCA_EVENT_CP_POR_FLAG,
	MCA_EVENT_WIRELESS_INT_CHANGE,
	MCA_EVENT_WIRELESS_EPP_MODE,
	MCA_EVENT_WIRELESS_AUDIO_PHONE_STS,
	MCA_EVENT_WIRELESS_MAGNETIC_QUIT_QC,
	MCA_EVENT_WIRELESS_PEN_HALL_CHANGE,
	MCA_EVENT_WIRELESS_PEN_PPE_HALL_CHANGE,
	MCA_EVENT_WIRELESS_SW_SET_QC_ICHG,
	MCA_EVENT_WIRELESS_SW_SET_THERMAL_ICHG,
	MCA_EVENT_WIRELESS_THERMAL_PHONE_FLAG,
	MCA_EVENT_WIRELESS_WLS_DEBUG,
	MCA_EVENT_PANEL_HBM_STATE_CHANGE,
	MCA_EVENT_OTG_DEVICE_PRESENT,
	MCA_EVENT_PPS_PTF,
	MCA_EVENT_IS_EU_MODEL,
	MCA_EVENT_PLATE_SHOCK,
	MCA_EVENT_MAX,
};

enum MCA_BATT_CHGR_STATUS_TYPE {
	MCA_BATT_CHGR_STATUS_INHIBIT,
	MCA_BATT_CHGR_STATUS_TRICKLE,
	MCA_BATT_CHGR_STATUS_PRECHARGE,
	MCA_BATT_CHGR_STATUS_FULLON,
	MCA_BATT_CHGR_STATUS_TAPER,
	MCA_BATT_CHGR_STATUS_TERMINATION,
	MCA_BATT_CHGR_STATUS_PAUSE,
	MCA_BATT_CHGR_STATUS_CHARGING_DISABLED,
	MCA_BATT_CHGR_STATUS_FAST_LINEAR,
};

struct mca_event_notify_data {
	const char *event;
	int event_len;
};

int mca_event_block_notify_register(unsigned int type,
				    struct notifier_block *nb);
int mca_event_block_notify_unregister(unsigned int type,
				      struct notifier_block *nb);
void mca_event_block_notify(unsigned int type, unsigned long event, void *data);
void mca_event_report_uevent(const struct mca_event_notify_data *n_data);

#endif /* _MCA_COMMON_MCA_EVENT_H_ */
