#ifndef _MCA_COMMON_MCA_CHARGE_MIEVENT_H_
#define _MCA_COMMON_MCA_CHARGE_MIEVENT_H_

enum charge_mievent_state_ele {
	MIEVENT_STATE_PLUG = 0,
	MIEVENT_STATE_END,
};

enum charge_dfx_event_index {
	CHARGE_DFX_PD_AUTH_FAILED = 0,
	CHARGE_DFX_CP_OPEN_FAILED,
	CHARGE_DFX_NOT_STANDARD_ADAPTER,
	CHARGE_DFX_RP_SHORT_VBUS_DETECTED,
	CHARGE_DFX_LPD_DETECTED,
	CHARGE_DFX_ANTI_BURN_TRIGGERED,
	CHARGE_DFX_ANTIBURN_ERR,
	CHARGE_DFX_BATTERY_AUTH_FAIL,
	CHARGE_DFX_BATTERY_MISSING,
	CHARGE_DFX_BATTERY_CYCLECOUNT,
	CHARGE_DFX_BATTERY_TEMP_COLD,
	CHARGE_DFX_BATTERY_TEMP_HOT,
	CHARGE_DFX_HIGH_TEMP_DISCHARGING,
	CHARGE_DFX_LOW_TEMP_DISCHARGING,
	CHARGE_DFX_SOC_NOT_FULL,
	CHARGE_DFX_FG_IIC_ERR,
	CHARGE_DFX_CP_ABSENT,
	CHARGE_DFX_CP_IBAT_OCP,
	CHARGE_DFX_CP_IBUS_OCP,
	CHARGE_DFX_CP_TDIE_HOT,
	CHARGE_DFX_CP_VAC_OVP,
	CHARGE_DFX_CP_VBAT_OVP,
	CHARGE_DFX_CP_VBUS_OVP,
	CHARGE_DFX_SMART_ENDURANCE_SOC_ERR,
	CHARGE_DFX_SMART_ENDURANCE_TRIGGERED,
	CHARGE_DFX_SMART_NAVIGATION_SOC_ERR,
	CHARGE_DFX_SMART_NAVIGATION_TRIGGERED,
	CHARGE_DFX_WLS_FASTCHG_FAIL,
	CHARGE_DFX_WLS_FOD_LOW_POWER,
	CHARGE_DFX_WLS_RX_IIC_ERR,
	CHARGE_DFX_WLS_RX_OCP,
	CHARGE_DFX_WLS_RX_OTP,
	CHARGE_DFX_WLS_RX_OVP,
	CHARGE_DFX_WLS_TRX_FOD,
	CHARGE_DFX_WLS_TRX_IIC_ERR,
	CHARGE_DFX_WLS_TRX_OCP,
	CHARGE_DFX_WLS_TRX_UVLO,
	CHARGE_DFX_MAX_NUM,
};

void mca_charge_mievent_report(int event_index, void *data, int size);
void mca_charge_mievent_set_state(enum charge_mievent_state_ele state, int value);

#endif /* _MCA_COMMON_MCA_CHARGE_MIEVENT_H_ */
