obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_protocol_pd_class.o

CFLAGS_mca_protocol_pd_class.o += -Wno-error=incompatible-pointer-types
CFLAGS_mca_protocol_pd_class.o += -Wno-error=incompatible-function-pointer-types
CFLAGS_mca_protocol_pd_class.o += -Wno-error=array-bounds
