ccflags-y += -I$(srctree)/drivers/misc/hwid

obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_strategy_quickchg.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_strategy_buckchg.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_charger_thermal.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_buckchg_jeita.o

CFLAGS_mca_strategy_quickchg.o += -Wno-error=format
