obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_protocol_class.o
obj-$(CONFIG_XM_POWER_SUPPLY)	+= protocol_pd/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= protocol_qc/

CFLAGS_mca_protocol_class.o += -Wno-error=incompatible-pointer-types
