subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mca/include
subdir-ccflags-y += -I$(srctree)/drivers/misc/hwid

obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_common/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_platform/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_strategy/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_business/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_hardware_monitor/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_smart_charge/
